# Generated by Django 3.2.7 on 2021-09-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostPerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputDate', models.DateField(auto_now_add=True)),
                ('inputTime', models.TimeField(auto_now_add=True)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unitsUsed', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unitsCost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'ordering': ['inputDate'],
            },
        ),
        migrations.CreateModel(
            name='TotalPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalPayment', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCostOverTime', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_paid', models.IntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('for_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_consumption.electricity')),
            ],
        ),
    ]
